exports.initial_witnesses = [
    "2OY57MQYKZSFDJXLDUFDEMNK7TMMBL5L",
    "J72HTGBVYZPEHMXLCPBJHH4OHZRASU2H",
    "L4XM66D4XJM7XKVOMSMDCZ5SJDWTLAVG",
    "QLQSJ4VMDHF5YD4VBVKMQ2XTATQS735Q",
    "WCKDY6NUPSTKA2UYBW5WFIZNPJ6VA2LG",
    "YHVFZ7IMRM7FZAVJ2YRJVIWSJEN5O7HB"
];

exports.MERCHANT_INTEGRATION_API = 'https://api.dagpay.io/api/invoices';
exports.WS_PROTOCOL = "ws://";
exports.port = 16611;
exports.getUnitPort = 28952;